before:
  hooks:
    - go mod tidy

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'

builds:
  - id: build
    main: .
    binary: gohttpd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: gohttpd
    builds:
      - build
    format: tar.gz
    # format_overrides:
    #   - goos: windows
    #     format: zip
    name_template: "gohttpd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README.md

release:
  github:
    owner: UlricQin
    name: gohttpd
  name_template: "v{{ .Version }}"
